language: go
go:
    - 1.9
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y tree
script:
    - go env
    - go list std
    - tree $(go env GOROOT)/src
    - echo $GOROOT
    - env | grep GOROOT
    - grep DefaultGoroot $(go env GOROOT)/src/runtime/internal/sys/zversion.go
    - go install
    - go vet ./...
    - go get honnef.co/go/tools/cmd/staticcheck
    - staticcheck ./...
